name = 'cherry-coaching'
main = 'src/index.js'
compatibility_date = '2022-06-30'

account_id = '8f6b70142fe60321f68d8d26f821d4d4'
workers_dev = true

[[d1_databases]]
binding = 'videoDB'
database_name = 'videos'
database_id = 'e4f459c8-cfc2-4ba0-8f67-1d7bea98d088'