name = 'cherry-coaching'
compatibility_date = '2024-09-23'
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = 'videoDB'
database_name = 'videos'
database_id = 'e4f459c8-cfc2-4ba0-8f67-1d7bea98d088'
preview_database_id = 'videoDB'